
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: qqqwwweee
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: stackoverflow_development

test:
  <<: *default
  database: stackoverflow_test
